COMPONENT_SRCDIRS=./src

# KEEP THIS IN SYNC WITH DEFINES IN include/mongoose.h!
# If they get out of sync, there will be undefined behavior.
MONGOOSE_CFLAGS = -DMG_ENABLE_HTTP_STREAMING_MULTIPART=1 \
			   -DMG_ENABLE_HTTP_WEBSOCKET=1 \
			   -DMG_ENABLE_BROADCAST=1
CFLAGS += ${MONGOOSE_CFLAGS}
CPPFLAGS += ${MONGOOSE_CFLAGS}
CXXFLAGS += ${MONGOOSE_CFLAGS}
