COMPONENT_SRCDIRS=./src ./port

# KEEP THIS IN SYNC WITH DEFINES IN include/mongoose.h!
# If they get out of sync, there will be undefined behavior.
MONGOOSE_CFLAGS = -DMG_ENABLE_HTTP_STREAMING_MULTIPART=1 \
			   -DMG_ENABLE_HTTP_WEBSOCKET=1 \
			   -DMG_ENABLE_CALLBACK_USERDATA=1 \
			   -DMG_ENABLE_BROADCAST=1  \
			   -DMG_ENABLE_SSL=1 \
                  -DMG_SSL_IF=MG_SSL_IF_MBEDTLS
CFLAGS += ${MONGOOSE_CFLAGS}
CPPFLAGS += ${MONGOOSE_CFLAGS}
CXXFLAGS += ${MONGOOSE_CFLAGS}
