language: cpp
compiler: gcc

before_install:
  - pip install --user --upgrade pip virtualenv
  - virtualenv venv
  - source venv/bin/activate

install: pip install -r requirements.txt

script:
  - source env.sh
  - cd src
  - TEST_COMPONENTS="." make -f Makefile.host GTEST_MAIN=1 V=1 host_build/hackvac_host
  - ./host_build/hackvac_host

cache:
  ccache: true
  directories:
    - third_party/esp-idf
    - components/mongoose/src
    - components/googletest
