language: cpp
compiler: gcc

before_install:
  - pip install --user --upgrade pip virtualenv
  - virtualenv venv
  - source venv/bin/activate

install:
  -  pip install -r requirements.txt
  -  pip install -r third_party/esp-idf/requirements.txt

script:
  - source env.sh
  - cd src
  - env
  - TEST_COMPONENTS="." make -f Makefile.host GTEST_MAIN=1 V=1 host_build/hackvac_host
  - ./host_build/hackvac_host

cache:
  ccache: true
  directories:
    - /home/travis/build/awong-dev/hackvac/third_party/esp-idf
    - /home/travis/build/awong-dev/hackvac/src/components/mongoose/src
    - /home/travis/build/awong-dev/hackvac/src/components/googletest
    - third_party/esp-idf
    - src/components/mongoose/src
    - src/components/googletest
