mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
component_include_dir := $(dir $(mkfile_path))include
mongoose_path := $(abspath $(dir $(mkfile_path))../mongoose)

host_test: ${COMPONENT_PATH}/host_test/*.cc ${COMPONENT_PATH}/src/task.cc ${COMPONENT_PATH}/src/httpd/*.cc
	c++ -Wno-format -pthreads -D_POSIX_THREADS=1 -DMOCK_ESP_IDF=1 -std=c++17 -Wno-unknown-attributes -I$(component_include_dir) -I$(mongoose_path)/include ${CPPFLAGS} $^ -o ${BUILD_DIR_BASE}/host_$@

