#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hackvac
#COMPONENTS :=  \
#  app_trace app_update app_flash bootloader bootloader_support cxx driver freertos heap \
#  esp32 esp_cxx esp_event esp_ringbuf esptool_py log micro-ecc newlib nvs_flash partition_table \
#  soc spi_flash tcp_transport, tcpip_adapter xtensa-debug-module \
#  mbedtls main mongoose lwip
#COMPONENTS = app_trace app_update asio aws_iot bootloader bootloader_support bt coap console cxx driver esp-tls esp32 esp_adc_cal esp_cxx esp_event esp_http_client esp_http_server esp_https_ota esp_ringbuf esptool_py ethernet expat fatfs freemodbus freertos heap idf_test jsmn json libsodium log lwip main mbedtls mdns micro-ecc mongoose mqtt newlib nghttp nvs_flash openssl partition_table protobuf-c protocomm pthread sdmmc smartconfig smartconfig_ack soc spi_flash spiffs tcp_transport tcpip_adapter test ulp vfs wear_levelling wifi_provisioning wpa_supplicant xtensa-debug-module

include $(IDF_PATH)/make/project.mk
