#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hackvac

ifdef HOST_TEST
CC := gcc
CXX := g++
BUILD_DIR_BASE=host_build
CONFIG_TOOLPREFIX=
endif

include $(IDF_PATH)/make/project.mk

